export const actionTypes = {
    uiOpenModal : "[ui] Open Modal Action",
    uiCloseModal : "[ui] Close Modal Action",
    eventSelected : "[event] Select Event",
    eventAddNew: "[event] Add new Event",
    eventAddSelectedSlot: "[event] Add Selected Slot Event",
    eventClearActive : "[event] Clear Active Event",
    eventUpdated: "[event] Event Updated",
    eventDeleted: "[event] Event Deleted",
    authCheckingLoginState: "[auth] Checking Login State",
    authLoginStateChecked: "[auth] Checking Login State Finished",
    authStartLogin: "[auth] Start Login",
    authLogin: "[auth] Login",
    authStartRegister: "[auth] Start Register",
    authRegister: "[auth] Register",
    authStartRefreshToken: "[auth] Start Refresh token",
    authRefreshToken: "[auth] Start token",
    authStartLogout: "[auth] Start Logout",
}